# Generated by Django 4.0.6 on 2022-07-06 04:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sem_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='Offerings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_no', models.CharField(max_length=225)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=220), default=list, size=None)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_year', models.CharField(max_length=225)),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.semester')),
            ],
            options={
                'verbose_name_plural': 'Offerings',
                'unique_together': {('offer_no', 'sem_id', 'academic_year')},
            },
        ),
    ]
