# Generated by Django 4.0.6 on 2022-07-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreated',
            fields=[
                ('id_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'AccountCreated',
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('counselor_id', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=220)),
                ('lastname', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Counselor',
            },
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('program_code', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'DegreeProgram',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=220)),
                ('firstname', models.CharField(max_length=220)),
                ('middlename', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=220)),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.department')),
            ],
            options={
                'verbose_name_plural': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(max_length=220)),
                ('school_name', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'School',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=220)),
                ('firstname', models.CharField(max_length=220)),
                ('middlename', models.CharField(max_length=220)),
                ('academic_year', models.CharField(max_length=225)),
                ('sem_id', models.CharField(max_length=220)),
                ('student_email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=220)),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.department')),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.degreeprogram')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.school')),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Studentload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_id', models.CharField(max_length=220)),
                ('academic_year', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Studentload',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('subject_title', models.CharField(max_length=220)),
                ('units', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectOfferings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_no', models.CharField(max_length=220)),
                ('subject_title', models.CharField(max_length=220)),
                ('school_days', models.CharField(max_length=220)),
                ('school_time', models.CharField(max_length=220)),
                ('sem_id', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=225)),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.department')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.faculty')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.subject')),
            ],
            options={
                'verbose_name_plural': 'SubjectOfferings',
            },
        ),
        migrations.DeleteModel(
            name='Offerings',
        ),
        migrations.AddField(
            model_name='studentload',
            name='offer_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.subjectofferings'),
        ),
        migrations.AddField(
            model_name='studentload',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.student'),
        ),
        migrations.AddField(
            model_name='department',
            name='school_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.school'),
        ),
        migrations.AddField(
            model_name='degreeprogram',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.faculty'),
        ),
        migrations.AddField(
            model_name='degreeprogram',
            name='school_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.school'),
        ),
        migrations.AddConstraint(
            model_name='subjectofferings',
            constraint=models.UniqueConstraint(fields=('offer_no', 'sem_id'), name='offer_no_and_sem_id_uniq_SubjectOfferings'),
        ),
        migrations.AddConstraint(
            model_name='studentload',
            constraint=models.UniqueConstraint(fields=('student_number', 'offer_no'), name='student_number_and_offer_no_uniq_Studentload'),
        ),
    ]
