# Generated by Django 4.0.6 on 2022-07-06 04:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0002_remove_offerings_id_alter_offerings_offer_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('counselor_id', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=220)),
                ('lastname', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Counselor',
            },
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('program_code', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=220)),
                ('counselor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.counselor')),
            ],
            options={
                'verbose_name_plural': 'DegreeProgram',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=220)),
                ('firstname', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=220)),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.department')),
            ],
            options={
                'verbose_name_plural': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_code', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'School',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=220)),
                ('firstname', models.CharField(max_length=220)),
                ('middlename', models.CharField(max_length=220)),
                ('gender', models.CharField(max_length=220)),
                ('avg_grade', models.CharField(max_length=220)),
                ('IQ', models.IntegerField()),
                ('birthdate', models.CharField(max_length=220)),
                ('hometown', models.CharField(max_length=220)),
                ('year', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=220)),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.degreeprogram')),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('subject_title', models.CharField(max_length=220)),
                ('units', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Subject',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.school'),
        ),
        migrations.AddField(
            model_name='degreeprogram',
            name='school_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.school'),
        ),
        migrations.CreateModel(
            name='SubjectOfferings',
            fields=[
                ('offer_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='followapp.offerings')),
                ('school_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=220), default=list, size=None)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(max_length=220)),
                ('academic_year', models.CharField(max_length=225)),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.department')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.faculty')),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.semester')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.subject')),
            ],
            options={
                'verbose_name_plural': 'SubjectOfferings',
                'unique_together': {('offer_no', 'sem_id', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Studentload',
            fields=[
                ('student_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='followapp.student')),
                ('academic_year', models.CharField(max_length=225)),
                ('offer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.offerings')),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followapp.semester')),
            ],
            options={
                'verbose_name_plural': 'Studentload',
                'unique_together': {('student_number', 'offer_code')},
            },
        ),
    ]
