# Generated by Django 4.0.6 on 2022-07-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0002_accountcreated_counselor_degreeprogram_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeprogram',
            name='faculty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.faculty'),
        ),
        migrations.AlterField(
            model_name='degreeprogram',
            name='school_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.school'),
        ),
        migrations.AlterField(
            model_name='department',
            name='school_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.school'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.degreeprogram'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.school'),
        ),
        migrations.AlterField(
            model_name='studentload',
            name='offer_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.subjectofferings'),
        ),
        migrations.AlterField(
            model_name='studentload',
            name='student_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.student'),
        ),
        migrations.AlterField(
            model_name='subjectofferings',
            name='department_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.department'),
        ),
        migrations.AlterField(
            model_name='subjectofferings',
            name='faculty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.faculty'),
        ),
        migrations.AlterField(
            model_name='subjectofferings',
            name='subject_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.subject'),
        ),
    ]
