# Generated by Django 4.0.6 on 2022-07-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0003_counselor_degreeprogram_department_faculty_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreated',
            fields=[
                ('id_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'AccountCreated',
            },
        ),
    ]
