# Generated by Django 4.0.6 on 2022-07-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0003_alter_degreeprogram_faculty_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdditionalInformation',
            fields=[
                ('student_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=220)),
                ('firstname', models.CharField(max_length=220)),
                ('middlename', models.CharField(max_length=220)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_contact_number', models.CharField(max_length=220)),
                ('mother_lastname', models.CharField(max_length=220)),
                ('mother_firstname', models.CharField(max_length=220)),
                ('mother_contact_number', models.CharField(max_length=220)),
                ('father_lastname', models.CharField(max_length=220)),
                ('father_firstname', models.CharField(max_length=220)),
                ('father_contact_number', models.CharField(max_length=220)),
                ('guardian_lastname', models.CharField(max_length=220)),
                ('guardian_firstname', models.CharField(max_length=220)),
                ('guardian_contact_number', models.CharField(max_length=220)),
                ('status', models.CharField(default='undone', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'StudentAdditionalInformation',
            },
        ),
    ]
