# Generated by Django 4.0.6 on 2022-07-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0004_studentadditionalinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
