# Generated by Django 4.0.6 on 2022-07-23 13:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0006_chessboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessboard',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), size=None), size=None),
        ),
    ]
