# Generated by Django 4.0.6 on 2022-07-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0008_referral_delete_chessboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=220)),
                ('notification_type', models.CharField(choices=[('automatic_referral', 'automatic_referral'), ('manual_referral', 'manual_referral'), ('appointment', 'appointment')], max_length=100)),
                ('is_read_student', models.BooleanField(default=False)),
                ('is_read_counselor', models.BooleanField(default=False)),
                ('extra_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=220)),
                ('schedDay', models.DateTimeField()),
                ('schedStartTime', models.TimeField()),
                ('schedEndTime', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Notification',
            },
        ),
    ]
