# Generated by Django 4.0.6 on 2022-07-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='firstname',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='lastname',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='middlename',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
