# Generated by Django 4.0.6 on 2022-07-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0010_referral_firstname_referral_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='feedback',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
