# Generated by Django 4.0.6 on 2022-07-25 02:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0011_alter_referral_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='counselor_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='degree_program',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='faculty_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=225, null=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='referral',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
