# Generated by Django 4.0.6 on 2022-07-25 02:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0012_alter_referral_counselor_id_alter_referral_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='faculty_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=225, null=True), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='referral',
            name='subject_referred',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), size=None), blank=True, null=True, size=None),
        ),
    ]
