# Generated by Django 4.0.6 on 2022-07-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0014_setschedulecounselor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=220)),
                ('notification_type', models.CharField(choices=[('feedback_teacher', 'feedback_teacher'), ('feedback_student', 'feedback_student')], max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('extra_id', models.IntegerField()),
                ('referral_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'NotificationFeedback',
            },
        ),
    ]
