# Generated by Django 4.0.6 on 2022-07-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0015_notificationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=10000)),
                ('remarks', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'CounselorFeedback',
            },
        ),
    ]
