# Generated by Django 4.0.6 on 2022-07-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0016_counselorfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickedDate', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Calendar',
            },
        ),
    ]
