# Generated by Django 4.0.6 on 2022-07-31 15:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0017_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), size=None), blank=True, null=True, size=None),
        ),
    ]
