# Generated by Django 4.0.6 on 2022-08-06 10:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0018_alter_referral_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='behavior_problem',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHEATING', 'CHEATING'), ('TARDINESS', 'TARDINESS'), ('DISRESPECTFUL', 'DISRESPECTFUL'), ('BAD ATTITUDE', 'BAD ATTITUDE'), ('OTHERS', 'OTHERS')], max_length=220, null=True),
        ),
    ]
