# Generated by Django 4.0.6 on 2022-08-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0019_alter_referral_behavior_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='choice',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
