# Generated by Django 4.0.6 on 2022-08-11 01:55

import django.contrib.postgres.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0021_newtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_referred', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), size=None), blank=True, null=True, size=None)),
                ('reasons', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), size=None), blank=True, null=True, size=None)),
                ('faculty_id', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=225, null=True), size=None), blank=True, null=True, size=None)),
                ('behavior_problem', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHEATING', 'CHEATING'), ('TARDINESS', 'TARDINESS'), ('DISRESPECTFUL', 'DISRESPECTFUL'), ('BAD ATTITUDE', 'BAD ATTITUDE'), ('OTHERS', 'OTHERS')], max_length=220, null=True)),
            ],
            options={
                'verbose_name_plural': 'ReferralDetails',
            },
        ),
        migrations.RemoveField(
            model_name='referral',
            name='behavior_problem',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='reasons',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='subject_referred',
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=225, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
