# Generated by Django 4.0.6 on 2022-08-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0023_alter_referraldetails_faculty_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referraldetails',
            name='faculty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='followapp.faculty'),
        ),
    ]
