# Generated by Django 4.0.6 on 2022-08-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0024_alter_referraldetails_faculty_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='units',
        ),
    ]
