# Generated by Django 4.0.6 on 2022-09-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0027_alter_meeting_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='creator',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
