# Generated by Django 4.0.6 on 2022-09-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0028_alter_meeting_created_alter_meeting_creator_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
