# Generated by Django 4.0.6 on 2022-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0029_delete_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program_name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
