# Generated by Django 4.0.6 on 2022-09-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0030_student_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectofferings',
            name='department_name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
