# Generated by Django 4.0.6 on 2022-10-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followapp', '0031_subjectofferings_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_counseled',
            field=models.BooleanField(default=False),
        ),
    ]
